LDLIBS=-lOpenCL -pthread -lm
#LDLIBS=-framework OpenCL


TARGETS+= erosion dilation difference complement opening closing gradient tophat bottomhat
TARGETS+= morphology morphologyTest morphologyRunningTimesTest

all: $(TARGETS)

